packadd! matchit

syntax enable

set textwidth=80
set shiftwidth=2
set expandtab
set autochdir
set grepprg='ag'

set directory=~/tmp,/tmp

nnoremap <esc><esc> :noh<cr>
noremap <C-p> :CtrlPMixed<cr>
noremap <C-f> :grep<space>
noremap <leader>e :e $MYVIMRC<cr>

autocmd! bufwritepost $MYVIMRC source $MYVIMRC
