set rtp+=/usr/local/opt/fzf

packadd! matchit

syntax enable

set textwidth=80
set shiftwidth=2
set expandtab
set autochdir
set directory=~/tmp,/tmp

" syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" misc
nnoremap <esc><esc> :noh<cr>
noremap <C-f> :grep<space>
noremap <leader>e :e $MYVIMRC<cr>

" ctrlp-ag
nnoremap <c-f> :CtrlPag<cr>
vnoremap <c-f> :CtrlPagVisual<cr>
nnoremap <leader>ca :CtrlPagLocate
nnoremap <leader>cp :CtrlPagPrevious<cr>

autocmd! bufwritepost $MYVIMRC source $MYVIMRC
