set rtp+=/usr/local/opt/fzf

packadd! matchit

syntax enable
filetype plugin on

set autochdir
set autoindent
set directory=~/tmp,/tmp
set expandtab
set hlsearch
set omnifunc=syntaxcomplete#Complete
set shiftwidth=2
set smartindent
set smarttab
set textwidth=80

" YCM
let g:ycm_semantic_triggers = {}
let g:ycm_semantic_triggers['typescript'] = ['.']

" Airline
let g:airline#extensions#tabline#enabled = 1

let g:syntastic_auto_loc_list = 0

" tsuquyomi
let g:tsuquyomi_disable_quickfix = 1
let g:syntastic_typescript_checkers = ['tsuquyomi']

" misc
nnoremap <esc><esc> :noh<cr>
noremap <C-f> :grep<space>
noremap <leader>e :e $MYVIMRC<cr>
noremap <C-h> <C-w><C-h>
noremap <C-j> <C-w><C-j>
noremap <C-k> <C-w><C-k>
noremap <C-l> <C-w><C-l>

" ctrlp-ag
nnoremap <c-f> :CtrlPag<cr>
vnoremap <c-f> :CtrlPagVisual<cr>
nnoremap <leader>ca :CtrlPagLocate
nnoremap <leader>cp :CtrlPagPrevious<cr>

" vim-prettier
nnoremap <leader>p :PrettierAsync<cr>

autocmd! bufwritepost $MYVIMRC source $MYVIMRC

" ft autocmds
autocmd FileType typescript setlocal completeopt=menu
